name: LoboBrowser
markdown: redcarpet
pygments: true
category-list: [features]
permalink: pretty
url: https://lobobrowser.org
cobrasite: //cobra.lobobrowser.org
communitysite: //forums.lobobrowser.org
extendsite: //extend.lobobrowser.org
blogsite: //blog.lobobrowser.org
docsite:   //docs.lobobrowser.org
legalsite: //legal.lobobrowser.org
